<?php
if (!defined('RSP_SITEMAP_PAGE_DEFAULT_LIMIT')) {
    define('RSP_SITEMAP_PAGE_DEFAULT_LIMIT', 50);
}
if (!defined('RSP_CLEANUP_BATCH_DEFAULT_LIMIT')) {
    define('RSP_CLEANUP_BATCH_DEFAULT_LIMIT', 500);
}
if (!defined('RSP_CACHED_SITEMAP_URLS_DEFAULT_EXPIRATION_TIME')) {
    define('RSP_CACHED_SITEMAP_URLS_DEFAULT_EXPIRATION_TIME', HOUR_IN_SECONDS / 2);
}
if (!defined('RSP_DATABASE_TABLE_DEFAULT_CLEANUP_FREQUENCY')) {
    define('RSP_DATABASE_TABLE_DEFAULT_CLEANUP_FREQUENCY', 'daily');
}
if (!defined('RSP_UPDATE_PRELOAD_TABLE_FREQUENCY')) {
    define('RSP_UPDATE_PRELOAD_TABLE_FREQUENCY', 'twicedaily');
}
if (!defined('RSP_IP_PROTECTION_TIME_THRESHOLD')) {
    define('RSP_IP_PROTECTION_TIME_THRESHOLD', HOUR_IN_SECONDS / 4);
}
if (!defined('RSP_CLEANUP_THREASHOLD_TIME')) {
    define('RSP_CLEANUP_THREASHOLD_TIME', '-30 days');
}
